package com.rest.api.commonutils;

import java.io.IOException;
import sun.misc.BASE64Decoder;


public class EsignedInvoice {

	  /* Decoding the Signed eInvoice start */
	  private void decodeSignedJWT(String signedText)
	  {
	    try {
	      @SuppressWarnings("restriction")
		  BASE64Decoder decoder = new BASE64Decoder();
	      String[]  splitSignedText = signedText.split("\\.");
	      String decodedSigned =new String(decoder.decodeBuffer(splitSignedText[0]));
	      decodedSigned = decodedSigned +"\n Content:"+(new String(decoder.decodeBuffer(splitSignedText[1])));
	      decodedSigned.replaceAll("\\\"", "");
	      decodedSigned.replaceAll("\"", "");
	      System.out.println("\nDecoded Text:" + decodedSigned);
	    } catch (IOException ex) {
	      //Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	    	System.out.println("Logger error "+ex.toString());
	     }
	   }
	  /* Decoding the Signed eInvoice end */
	  
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		StringBuffer strBuffer = new StringBuffer("eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiQWNrTm9cIjoxNzEwMDAwMDA1NCxcIkFja0R0XCI6XCIyMDE5LTEyLTI1IDEyOjAzOjAwXCIsXCJUYXhTY2hcIjpudWxsLFwiVmVyc2lvblwiOlwiMS4wXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIixcIlRyYW5EdGxzXCI6e1wiQ2F0Z1wiOlwiQjJCXCIsXCJSZWdSZXZcIjpcIlJHXCIsXCJUeXBcIjpcIlJFIFwiLFwiRWNtVHJuXCI6XCJOXCIsXCJFY21Hc3RpblwiOlwiXCJ9LFwiRG9jRHRsc1wiOntcIlR5cFwiOlwiSU5WXCIsXCJOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiT3JnSW52Tm9cIjpcIjEyMzMyMTEyMzMyMTEyMzJcIn0sXCJTZWxsZXJEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIlRyYWRlIE5hbWUxXCIsXCJCbm9cIjpcIjFcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCJcIixcIkxvY1wiOlwiTG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJjQHh5ei5jb21cIn0sXCJCdXllckR0bHNcIjp7XCJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJUcmRObVwiOlwiVHJhZGUgTmFtZTFcIixcIkJub1wiOlwiMVwiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIlwiLFwiTG9jXCI6XCJMb2NhdGlvblwiLFwiRHN0XCI6XCJcIixcIlBpblwiOjU2MDA0MyxcIlN0Y2RcIjoyOSxcIlBoXCI6bnVsbCxcIkVtXCI6XCJhYmNAeHl6LmNvbVwifSxcIkRpc3BEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIm5hbWUgXCIsXCJCbm9cIjpcIjEyM1wiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIjJcIixcIkxvY1wiOlwibG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJDQFhZWi5DT01cIn0sXCJTaGlwRHRsc1wiOntcIkdzdGluXCI6XCIyOUFBR1BCODY3OEwxWjFcIixcIlRyZE5tXCI6XCJuYW1lIFwiLFwiQm5vXCI6XCIxMjNcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCIyXCIsXCJMb2NcIjpcImxvY2F0aW9uXCIsXCJEc3RcIjpcIlwiLFwiUGluXCI6NTYwMDQzLFwiU3RjZFwiOjI5LFwiUGhcIjpudWxsLFwiRW1cIjpcImFiQ0BYWVouQ09NXCJ9LFwiSXRlbUxpc3RcIjpbe1wiUHJkTm1cIjpcIldoZWF0XCIsXCJQcmREZXNjXCI6XCJXaGVhdCBkZXNjXCIsXCJIc25DZFwiOlwiMTAwMVwiLFwiQmFyY2RlXCI6bnVsbCxcIlF0eVwiOjEsXCJGcmVlUXR5XCI6bnVsbCxcIlVuaXRcIjpcIktHU1wiLFwiVW5pdFByaWNlXCI6MCxcIlRvdEFtdFwiOjAsXCJEaXNjb3VudFwiOjAsXCJPdGhDaHJnXCI6MCxcIkFzc0FtdFwiOjAsXCJDZ3N0UnRcIjozLFwiU2dzdFJ0XCI6MyxcIklnc3RSdFwiOjAsXCJDZXNSdFwiOjAsXCJDZXNOb25BZFZhbFwiOjAsXCJTdGF0ZUNlc1wiOjM2LFwiVG90SXRlbVZhbFwiOjIzNDMyfV0sXCJWYWxEdGxzXCI6e1wiQXNzVmFsXCI6MTAsXCJDZ3N0VmFsXCI6MixcIlNnc3RWYWxcIjoyLFwiSWdzdFZhbFwiOjAsXCJDZXNWYWxcIjowLFwiU3RDZXNWYWxcIjowLFwiQ2VzTm9uQWRWYWxcIjowLFwiRGlzY1wiOjAsXCJPdGhDaHJnXCI6MCxcIlRvdEludlZhbFwiOjB9LFwiRXhwRHRsc1wiOntcIkV4cENhdFwiOlwiU0VaXCIsXCJXdGhQYXlcIjpcIk5cIixcIlNoaXBCTm9cIjpcIlwiLFwiU2hpcEJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiUG9ydFwiOlwiXCIsXCJJbnZGb3JDdXJcIjoyMzQ0NSxcIkZvckN1clwiOlwiQkRUXCIsXCJDbnRDb2RlXCI6XCJCRFwifSxcIlBheUR0bHNcIjp7XCJOYW1cIjpcIlwiLFwiTW9kZVwiOlwiQ0FTSFwiLFwiRmluSW5zQnJcIjpcIlwiLFwiUGF5VGVybVwiOlwiMTAwMVwiLFwiUGF5SW5zdHJcIjpcIlwiLFwiQ3JUcm5cIjpcIlwiLFwiRGlyRHJcIjpcIlwiLFwiQ3JEYXlcIjoyLFwiQmFsQW10XCI6MixcIlBheUR1ZUR0XCI6XCIyMDE5LTExLTI4XCIsXCJBY2N0RGV0XCI6XCIxMFwifSxcIlJlZkR0bHNcIjp7XCJJbnZSbWtcIjpcIjBcIixcIkludlN0RHRcIjpcIjIwMTktMTEtMjhcIixcIkludkVuZER0XCI6XCIyMDE5LTExLTI4XCIsXCJQcmVjSW52Tm9cIjpcIlwiLFwiUHJlY0ludkR0XCI6XCIyMDE5LTExLTI4XCIsXCJJbnZSZWZOb1wiOlwiMFwiLFwiUmVjQWR2UmVmXCI6XCJcIixcIlRlbmRSZWZcIjpcIlwiLFwiQ29udHJSZWZcIjpcIjEwXCIsXCJFeHRSZWZcIjpcIjJcIixcIlByb2pSZWZcIjpcIlwiLFwiUE9SZWZcIjpcIlwifX0iLCJpc3MiOiJOSUMifQ.II0jejF0wOrY0CPwIb6oQsSBYilvFSNHZqQJHYOsFt7txrpAvLlCEo4CDNUhPZGWZ6IeERuoY2ScXKNIsCIMQR_9dc0E_fmsaN5XUscxBV3nqPNIkusFcmzjxu59sT8MzcaFqDWfqHunkA-klW40M7oVy6HtL5eI0zbmNoZpdl2yB1Fxfx5AF_vcDv9vWV2u6i39XQ0KdTSbkTAVStdXHix2hE0TlHtHB9Tqt7i9umNPJc_Uf5Kpn4qHiOPvFT2uxhw1N7bIU00cc-PDIqzlLk2VnLb2Zko7wSgYAMrf5G1hn5Op4lbyQe9EwxOPcvJPjJBJsoOmFTbxd1IRgewm7g");
		//StringBuffer qrCodeData = new StringBuffer("eyJhbGciOiJSUzI1NiIsImtpZCI6IjExNUY0NDI2NjE3QTc5MzhCRTFCQTA2REJFRTkxQTQyNzU4NEVEQUIiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJFVjlFSm1GNmVUaS1HNkJ0dnVrYVFuV0U3YXMifQ");
		//StringBuffer strBuffer = new StringBuffer("11f8ef701fe294d4a14aad0b12457e62775d0fdc41a0acf05b74fbb2ddc47acb");
		new EsignedInvoice().decodeSignedJWT(strBuffer.toString());
	}

}
